routes:
  hello:
    method:   'GET'
    path:     '/hello'
    class:    '\Demo\Routes\Hello'
    function: 'helloRequest'
    dependency:
      - '\Demo\Dependency\NumberProvider'

  bar:
    method:   'GET'
    path:     '/bar/[:name]'
    class:    '\Demo\Routes\Bar'
    function: 'foo'
